config/routes.rb
Rails.application.routes.draw do
  root 'posts#home'
  
  get 'users/new'

  get 'sessions/new'

  #Post
  #creat
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :trips, only: [:index, :new, :create, :destroy] 
  
  
  
  get '/posts/new' => 'posts#new'
  post '/posts/create' => 'posts#create'
  get '/pictures/index' => 'pictures#index'
  
  #sign up
  get 'login' => 'sessions#new' 
  post 'login' => 'sessions#create' 
  get 'logout' => 'sessions#destroy'
 # 기본 제공이아니라 특이함

  
  
  
  #travel 
  get '/trips/index' => 'trips#index'
  get '/trips/new' => 'trips#new'
  get '/trips/create' => 'trips#create'
 
  get '/trips/show/:trip_id' => 'trips#show'
  get '/trips/destroy/:trip_id' => 'trips#destroy'

  #read 
 
  get '/posts/index' => 'posts#index'
  get '/posts/show/:post_id' => 'posts#show'
 #get '/posts/show2' => 'posts#show2'

  #get story
  get '/stories/newstory' => 'stories#newstory'
  
  #update
  get '/posts/edit/:post_id' => 'posts#edit'
  post '/posts/update/:post_id' => 'posts#update'
  
  #delete
  post '/posts/destory/:post_id' => 'posts#destory'



 #comments
  #create
  post '/posts/show/:post_id/comments/create' => 'comments#create'
  #destroy
  post '/posts/show/:post_id/comments/destroy/:comment_id' => 'comments#destroy'

  #comments
  #create
  post '/trips/show/:trip_id/comments/create' => 'comments#create'
  #destroy
  post '/trips/show/:trip_id/comments/destroy/:comment_id' => 'comments#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    #댓글기능
     belongs_to :trip
end

app/models/post.rb
class Post < ActiveRecord::Base
    #post
     has_many:comments, :dependent=> :destroy
    
  
end

app/models/trip.rb
class Trip < ActiveRecord::Base
    
    has_many:comments, :dependent=> :destroy
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   
   
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    before_save { self.email = email.downcase } #save하기전에 작동하는 코드 사용자에게 받아온 email을 소문자로 바꿔서 저장  
    VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 255},
                        format: {with: VALID_EMAIL_REGEX},
                        uniqueness: {case_sensitive: false}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  
  include SessionsHelper
  
  def authenticate
    redirect_to new_session_path if !user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @comment= Comment.new
        @comment.email=current_user.email
        @comment.name=params[:input_name]
        @comment.content=params[:input_comment]
        @comment.trip_id=params[:trip_id]
        @comment.save
        redirect_to "/trips/show/#{params[:trip_id]}"
    end
    
    def destroy
        @comment=Comment.find(params[:comment_id])
        @comment.destroy
        redirect_to "/trips/show/#{params[:trip_id]}"
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    #create part 
    def new
    #그냥 화면 구성 
    end
    
    def create
    #입력 데이터 실제 디비에 저장
    
        @post=Post.new #post는 모델이름 ! 
        @post.title=params[:input_title] #안에 내용 받아와 
        @post.content=params[:input_content]
        @post.save
            redirect_to "/posts/show/#{@post.id}" #show post on display 
        #다시돌아가 
    end
    
   
    
    
    
    #read part
    def index
        @posts=Post.all  #get all post
        @users =User.all
    end
    
    def show
        #한개의 post를 보여주는 view
        @post=Post.find(params[:post_id]) #id에 해당하는 post를 가져와라 
        #find는 id로만 검색가능 
        @comments=Comment.where(post_id: params[:post_id]) #where 조건문 걸어서 params에서 받아온 
        #post_id가 post_id랑 같은지 확인하기 
        #params[:post_id]는 routes에서 get/// post_id에서 받아온것이고 params안에는 무조건 같은 변수가 와야함
    end

    #update
    def edit 
        
        @post=Post.find(params[:post_id])
    end
    
    def newstory #저장된 스토리 다가져와 
        @story=Story.all 
    end
    
    
    def update
        #입력된 값 가져와서 save다시해라 ! 
        @post=Post.find(params[:post_id])
        @post.title=params[:input_title]
        @post.content=params[:input_content]
        @post.save
        #그 post다시 show해라 
        redirect_to "/posts/show/#{@post.id}"
    end
    
    
    #delete
    def destory
        #route에서 받아온 post_id
        @post =Post.find(params[:post_id])
        @post.destroy
        #home 화면으로 보내준다 
        redirect_to '/'
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController #상속 

  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:alert] = 'Invalid email/password combination'
      redirect_to new_session_path
    end
  end
  
  def destroy
    log_out
    redirect_to :root
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    
    
    
    def index
        @trip=Trip.new
        @trips=Trip.all  #get all post
    end
    

     def new
         @trip=Trip.new
         #@trip.writer
    #그냥 화면 구성 
    end
    
     def create
      @trip = Trip.new(trip_params)
     
          @trip.writer=current_user.email #current user ID
          if @trip.save
             redirect_to trips_path, notice: "The trip #{@trip.title} has been uploaded."
          else
             render "new"
          end
      
    end
    def show
        #한개의 post를 보여주는 view
        @trip=Trip.find(params[:trip_id]) #id에 해당하는 post를 가져와라 
        #find는 id로만 검색가능 
        @comments=Comment.where(trip_id: params[:trip_id]) #where 조건문 걸어서 params에서 받아온 
        #post_id가 post_id랑 같은지 확인하기 
        #params[:post_id]는 routes에서 get/// post_id에서 받아온것이고 params안에는 무조건 같은 변수가 와야함
    end
   
    def destroy
        @trip = Trip.find(params[:trip_id])
        @trip.destroy
        redirect_to '/trips/index'
    end
 
   
   
 
    def trip_params
      params.require(:trip).permit(:content, :title, :attachment)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users =User.all
  end
  
  def new
  end
  def create
    User.create(email: params[:email],
                password: params[:password],
                password_confirmation: params[:password_confirmation],
                name: params[:name])
    redirect_to '/'
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 전달된 사용자로 로그인
  def log_in(user)
    session[:user_id] = user.id
  end

  # 현재 로그인 한 사용자를 반환(로그인 한 경우에만)
  # 널일경우 뒤에꺼 실행해서 집어넣는다. 널이 아니면 처리하지 않아서 DB를 한번만 읽게한다. 
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    # (1)
    # if @current_user.nil?
    #   @current_user = User.find_by(id: session[:user_id])
    # else
    #   @current_user = @current_user
    # end
    # (2)
    # @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  # 로그인 되어있다면 true 를 그렇지 않다면 false 를 반환
  def user_signed_in?
    !current_user.nil?
  end

  # session[:user_id]와 @current_user 삭제
  def log_out
    session.delete(:user_id)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <% if user_signed_in? %>
    <li><%= current_user.name %></li>
    <li><%= current_user.email %></li>
    <li><%= link_to 'Sign out', logout_path, method: 'delete' %></li>
  <% else %>
    <li><%= link_to 'Sign in', new_session_path %></li>
    <li><%= link_to 'Sign up', new_user_path %></li>
<% end %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<%= csrf_meta_tags %>
</head>
<body>
<% if session[:user_id] %>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<hr>
<h1 style="text-align:center; margin-top:20px;"><%= @post.id %>th Post Edit </h1>
<br>
<div class="container">

<form action=="/posts/update/<%= @post.id %>" method="post">
    <div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <input type="text" name="input_title" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="<%= @post.title%>">
   </div>
    <div class="form-group">
    <label for="exampleTextarea">contents</label>
    <textarea class="form-control" name="input_content" id="exampleTextarea" rows="5" placeholder="<%= @post.content%>" ></textarea>
  </div>
  
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

app/views/posts/home.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/paper/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    
    <!-- Bootstrap Core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/stylish-portfolio.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="assets/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
     <header id="top" class="header">
        
         <div class="text-vertical-center" style="color:white">
            <h1 > Welcome to Hye In's blog ♡</h1>
            <h3> # Korean # IT # Travel # Likelion ! </h3>
            <br>
            <a href="#about" class="btn btn-dark btn-lg">made by HyeIn </a>
        </div>
    </header>   
    <ul class="nav nav-pills categories">
        <li class="active"><a href="#"> Introduction </a></li>
        <li><a href="/posts/index"> Post </a></li>
        <li>
           
                <a href="/trips/index">  Travel </a>
            
        </li>
       
        
        <li><a href="#">Techniques </a></li>
    </ul>
    
</head>

<body>
 
    <div class="container post">
        <div class="row">
            <div class="col-md-6 post-title">
                <h1>Welcome to Hyein's <br>world</h1>
                <p class="author"><strong>hyein</strong> <span class="text-muted">May 25th 2017 </span></p>
            </div>
            <div class="col-md-6 col-md-offset-0 post-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sem quam, scelerisque vitae sem non, ornare condimentum leo. Vivamus eros tortor, tincidunt et viverra ac, gravida eu augue. Interdum et malesuada fames ac ante ipsum primis
                    in faucibus. Praesent nibh ex, hendrerit at tellus sed, laoreet suscipit leo. </p>
                <p>Curabitur cursus ac quam sit amet mattis. Donec lacinia massa id libero tincidunt, sed ultricies magna eleifend. Integer porta consectetur ipsum sed porttitor. Praesent sed convallis nisi. Mauris eget commodo sem. Sed auctor commodo quam
                    eu semper. </p>
                <p>Sed mollis, urna eu tempus facilisis, diam tellus aliquam tortor, et vestibulum ante quam non justo. Nullam luctus rutrum mattis. Maecenas in pharetra mi, vel mollis odio. </p>
                <figure><img src="/assets/bali.jpg" height="400" width="580">
                
                    <figcaption> In Bali </figcaption>
                </figure>
                <p> I love traveling ! I went to plenty of countries in 2016. I got millions picture ^-^. If you feel like discovering my trip click on menu above.  </p>
            </div>
        </div>
    </div>
    
        <!-- Call to Action -->
    <aside class="call-to-action" >
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>You wanna come to my face book ! ? </h3>
                    
                     <a href="https://www.facebook.com/profile.php?id=100003225818091"><img src="/assets/facebook.png" height="10px" width="10px" ></a>
                      <h1>click ! </h1>
                       </div>
            </div>
        </div>
    </aside>
    
    
    
    
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>address where I am</strong>
                    </h4>
                    <p>Korea 
                        <br>You are welcome to Kroea ! </p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> 010-5124-5312</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">gn00090@naver.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; Your Website 2017</p>
                </div>
            </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

    <!-- jQuery -->
    <script src="/assets/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    //#to-top button appears after scrolling
    var fixed = false;
    $(document).scroll(function() {
        if ($(this).scrollTop() > 250) {
            if (!fixed) {
                fixed = true;
                // $('#to-top').css({position:'fixed', display:'block'});
                $('#to-top').show("slow", function() {
                    $('#to-top').css({
                        position: 'fixed',
                        display: 'block'
                    });
                });
            }
        } else {
            if (fixed) {
                fixed = false;
                $('#to-top').hide("slow", function() {
                    $('#to-top').css({
                        display: 'none'
                    });
                });
            }
        }
    });
    // Disable Google Maps scrolling
    // See http://stackoverflow.com/a/25904582/1607849
    // Disable scroll zooming and bind back the click event
    var onMapMouseleaveHandler = function(event) {
        var that = $(this);
        that.on('click', onMapClickHandler);
        that.off('mouseleave', onMapMouseleaveHandler);
        that.find('iframe').css("pointer-events", "none");
    }
    var onMapClickHandler = function(event) {
            var that = $(this);
            // Disable the click handler until the user leaves the map area
            that.off('click', onMapClickHandler);
            // Enable scrolling zoom
            that.find('iframe').css("pointer-events", "auto");
            // Handle the mouse leave event
            that.on('mouseleave', onMapMouseleaveHandler);
        }
        // Enable map zooming with mouse scroll when the user clicks the map
    $('.map').on('click', onMapClickHandler);
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    
    
</body>

</html>

app/views/posts/index.html.erb
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

     <!-- Bootstrap Core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/stylish-portfolio.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="assets/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">

   

    <!-- Temporary navbar container fix -->
    <style>
    .navbar-toggler {
        z-index: 1;
    }
    
    @media (max-width: 576px) {
        nav > .container {
            width: 100%;
        }
    }
    </style>

</head>


<body>
     <header id="top" class="header2">
        
         <div class="text-vertical-center" style="color:white">
            <h1> Hye In ♡</h1>
            <h3> # Korean # IT # Travel # Likelion ! </h3>
            <br>
            <a href="#about" class="btn btn-dark btn-lg">made by HyeIn </a>
        </div>
    </header>   
    <ul class="nav nav-pills categories">
        <li><a href='/'> Introduction </a></li>
        <li  class="active"><a href="/posts/index"> Post </a></li>
        <li><a href="/trips/index"> Travel </a></li>
        <li><a href="#">Locations </a></li>
        <li><a href="#">Techniques </a></li>
    </ul>    
    
<div class="container">
     <br><br>
     <a href="/posts/new" class="btn btn-dark btn-lg">New Post </a>
   
    <br><br>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Number </th>
                    <th>Title</th>
                </tr>
            </thead>
            <tbody>
            <% @posts.each do |post| %>
                <tr>
                    <td><%= post.id %></td>
                    <td><a href="/posts/show/<%= post.id %>">  <%= post.title %></a></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    </div>
    
     <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>address where I am</strong>
                    </h4>
                    <p>north of Daegu
                        <br>Daegu , KOREA </p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> 010-5124-5312</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">gn00090@naver.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; Your Website 2017</p>
                </div>
            </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

</body>

app/views/posts/new.html.erb
<hr>
<h1 style="text-align:center; margin-top:20px;">Post </h1>
<br>

<div class="container">
<form action="/posts/create" method="post">
  <div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <input type="text" name="input_title" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="what is title ? ">
   </div>
  
  <div class="form-group">
    <label for="exampleTextarea">contents</label>
    <textarea class="form-control" name="input_content" id="exampleTextarea" rows="5" placeholder="put contents ! " ></textarea>
  </div>
 
 
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</div>




<!--
<h1>Post insert ! </h1>
<form action="/posts/create" method="post">
    <p>제목</p>
    <input type="text" name="input_title">
    <p>내용</p>
    <input type="text" name="input_content">
    <p>제출</p>
    <input type="submit">
</form>

-->

app/views/posts/new2.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>






<body>
    <header><img src="assets/img/IMG_0729.jpg">
        <div class="page-header">
            <h1>POST <small>by anyone</small></h1></div>
    </header>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Number </th>
                    <th>Title</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Cell 1</td>
                    <td>Cell 2</td>
                </tr>
                <tr>
                    <td>Cell 3</td>
                    <td>Cell 4</td>
                </tr>
            </tbody>
        </table>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

app/views/posts/show.html.erb
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/paper/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    
    <!-- Bootstrap Core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/stylish-portfolio.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="assets/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
     <header id="top" class="header">
        
         <div class="text-vertical-center" style="color:white">
            <h1 > Welcome to Hye In's blog ♡</h1>
            <h3> # Korean # IT # Travel # Likelion ! </h3>
            <br>
            <a href="#about" class="btn btn-dark btn-lg">made by HyeIn </a>
        </div>
    </header>   
    <ul class="nav nav-pills categories">
        <li class="active"><a href="#"> Introduction </a></li>
        <li><a href="/posts/index"> Post </a></li>
        <li>
           
                <a href="/trips/index">  Travel </a>
            
        </li>
       
        
        <li><a href="#">Techniques </a></li>
    </ul>
    
</head>
<body>

    <div class="container">

        <div class="row">

            <!-- Post Content Column -->
            <div class="col-lg-8">
    
                    <!-- Title -->
               
                <!-- Date/Time -->
                
                
               
                <h2 class="mt-4"> <%= @post.title%></h2> <!--title-->
                
                
                <p class="lead"> <%= @post.content%></p> <!--contents-->
                <hr>
                <p>Posted on <%= @post.created_at%></p>
                <p>Updated on <%= @post.updated_at%></p>
                <hr>
                
                
                
                <div class="media mb-4">
                    <div class="media-body">
 
                        <button type="submit" ><a href="/posts/index" > Go back list </a></button>
                        <button type="submit" ><a href="/posts/destory/<%= @post.id%>" data-confirm="진짜로 삭제 ? "> Delete </a></button>
                        <button type="submit" ><a href="/posts/edit/<%= @post.id%>" > Edit </a></button>
                        
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/users/index.html.erb
  <% @users.each do |u| %>
       <li> <%=u.name%> </li>
   <% end %>